---
# tasks file for webserver-install

- name: Install httpd in centOS
  yum:
    name: httpd
    state: present
    update_cache: yes
  #when: ansible_distribution == "CentOS"

- name: Start service in centOS
  service:
    name: httpd
    state: started
    enabled: yes
  #when: ansible_distribution == "CentOS"

- name: Install apache2 in Ubuntu
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Start apache2 service in Ubuntu
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Copy index file 
  copy:
    src: index.html
    dest: /var/www/html/
    backup: yes
