---
# tasks file for post-install
- name: Install ntp agent on centOS
  yum:
    name: "{{ item }}"
    state: present
  when: ansible_distribution == "CentOS"
  loop:
    - chrony
    - wget
    - git
    - zip
    - unzip

- name: Start service on centOS
  service:
    name: chronyd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: Install ntp agent on ubuntu
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
  loop:
    - ntp
    - wget
    - git
    - zip
    - unzip

- name: Start service on Ubuntu
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Banner file
  copy:
    content: 'This server is manged by ansible. No manual changes please'
    dest: /etc/motd

- name: Create a folder
  file:
    path: " {{mydir}}"
    state: directory

- name: Deploy NTP agent conf on centOS
  template:
    src: ntpconf_centos
    dest: /etc/chrony.conf
    backup: yes
  when: ansible_distribution == "CentOS"
  notify:
    - Restart service on centOS

- name: Deploy NTP agent conf on ubuntu
  template:
    src: ntpconf_ubuntu
    dest: /etc/ntp.conf
    backup: yes
  when: ansible_distribution == "Ubuntu"
  notify:
    - Restart service on Ubuntu

- name: Dump file
  copy:
    src: myfile.txt
    dest: /tmp/myfile.txt

- name: Set timezone to America/Sao_Paulo
  community.general.timezone:
    name: America/Sao_Paulo
