- name: Provisionando os balancers
  hosts: balancers
  become: yes
  tasks:
  - name: Inclui o arquivo de tarefas especificas da distribuicao
    include_tasks: '{{ ansible_os_family|lower }}.yml'
  - name: Garantindo que os pacotes haproxy e keepalived estejam instalados
    package:
      name: haproxy, keepalived
      state: present
  - name: Garantindo o arquivo de configuração do HAProxy
    template:
      src: files/haproxy.cfg
      dest: /etc/haproxy/haproxy.cfg
    register: haproxy_config
  - name: Garantindo o arquivo de configuração do keepalived
    template:
      src: files/keepalived.conf
      dest: /etc/keepalived/keepalived.conf
    notify: Restart keepalived
  - name: Garantindo que o serviço do HAProxy esteja rodando
    service:
      name: haproxy
      state: started
      enabled: yes
  - name: Garantindo que o serviço do HAProxy receba as configurações
    service:
      name: haproxy
      state: reloaded
    when: haproxy_config.changed == true
  - name: Garantindo que o serviço do keepalived esteja rodando
    service:
      name: keepalived
      state: started
      enabled: yes
  - name: Garante que o kernel esteja ajustado para o HAProxy
    lineinfile:
      path: /etc/sysctl.conf
      line: '{{ item }}'
      state: present
    loop:
    - 'net.ipv4.tcp_rmem            = 4096 16060 262144'
    - 'net.ipv4.tcp_wmem            = 4096 16384 262144'
    - 'net.ipv4.tcp_tw_reuse        = 1'
    - 'net.ipv4.ip_local_port_range = 1024 65023'
    - 'net.ipv4.tcp_max_syn_backlog = 60000'
    - 'net.ipv4.tcp_fin_timeout     = 30'
    - 'net.ipv4.tcp_synack_retries  = 3'
    - 'net.ipv4.ip_nonlocal_bind    = 1'
    - 'net.core.somaxconn           = 60000'
  - name: Garante que o kernel receba as configurações
    service:
      name: systemd-sysctl
      state: restarted

  handlers:
  - name: Restart keepalived
    service:
      name: keepalived
      state: reloaded
