- name: Garantindo que o firewall esteja inicializado
  service:
    name: firewalld
    state: started
    enabled: yes
- name: Garantindo que as portas 80 e 443 estejam abertas
  ansible.posix.firewalld:
    service: '{{ item }}'
    state: enabled
    immediate: yes
    permanent: yes
  loop:
  - http
  - https
- name: Garantindo que o protocolo VRRP esteja liberado
  ansible.posix.firewalld:
    rich_rule: rule protocol value="vrrp" accept
    state: enabled
    immediate: yes
    permanent: yes
- name: Garantindo que python3-libsemanage esteja instalado
  yum:
    name: python3-libsemanage
    state: present
- name: Garantindo regra selinux para HAProxy
  ansible.posix.seboolean:
    name: haproxy_connect_any
    state: yes
    persistent: yes
