---
- name: Instalando epel-release
  dnf: name=epel-release state=latest

- name: Update S.O.
  dnf: name=* state=latest update_cache=yes

- name:
  dnf:
    name:
      - vim
      - tree
      - wget
      - curl
      - default-jdk
  